services:
  db:
    image: postgres:15
    container_name: postgres_lensora
    restart: always
    command: ["postgres", "-c", "listen_addresses=*"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hoalt@2005
      POSTGRES_DB: LensoraDB
    ports:
      - "0.0.0.0:${DB_PORT:-5433}:5432" # Publish cho mọi interface của máy host
    volumes:
      - lensora_db_data:/var/lib/postgresql/data # Đảm bảo rằng dữ liệu được lưu trữ bền vững ngay cả khi container bị xóa

  backend:
    build: backend
    container_name: java_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/LensoraDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Hoalt@2005

volumes:
  lensora_db_data: