CREATE TABLE IF NOT EXISTS categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(255),
    type VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(255),
    password VARCHAR(255),
    email VARCHAR(255),
    role VARCHAR(50),
    trust_score INTEGER NOT NULL DEFAULT 100
);

CREATE TABLE IF NOT EXISTS products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT,
    product_name VARCHAR(255),
    brand VARCHAR(255),
    description TEXT,
    price DOUBLE PRECISION,
    stock_quantity INTEGER,
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories (category_id)
);

CREATE TABLE IF NOT EXISTS assets (
    asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT,
    model_name VARCHAR(255),
    brand VARCHAR(255),
    description TEXT,
    daily_rate DOUBLE PRECISION,
    deposit_value DOUBLE PRECISION,
    status VARCHAR(50),
    serial_number VARCHAR(255),
    CONSTRAINT fk_assets_category
        FOREIGN KEY (category_id) REFERENCES categories (category_id)
);

CREATE TABLE IF NOT EXISTS images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT,
    url TEXT,
    is_primary BOOLEAN,
    type VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS carts (
    cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    product_id BIGINT,
    quantity INTEGER
);

CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    order_date TIMESTAMP WITHOUT TIME ZONE,
    total_amount DOUBLE PRECISION,
    shipping_address TEXT,
    status VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    product_id BIGINT,
    quantity INTEGER,
    price_at_purchase DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    entity_id BIGINT,
    rating INTEGER,
    comment TEXT,
    type VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS rentals (
    rental_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    asset_id BIGINT,
    start_date DATE,
    end_date DATE,
    return_date DATE,
    deposit_fee DOUBLE PRECISION,
    total_rent_fee DOUBLE PRECISION,
    penalty_fee DOUBLE PRECISION,
    status VARCHAR(50),
    CONSTRAINT fk_rentals_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_rentals_asset
        FOREIGN KEY (asset_id) REFERENCES assets (asset_id)
);