-- Backfill missing tables and columns for legacy databases so the app can start.

ALTER TABLE products ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE assets ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE;

CREATE TABLE IF NOT EXISTS product_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT,
    url TEXT NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS asset_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT,
    url TEXT NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO product_images (product_id, url, is_primary)
SELECT
    (SELECT product_id FROM products WHERE product_name = 'UHS-II SD Card 128GB' AND brand = 'SanDisk' LIMIT 1),
    'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQxXW0GwBBacRvrJkWFEAtVj-cv67eSUgl-AhUo32OnDTiTbKpyjT8pfgoTH1JTddWgHPXNjjk28nYg2u7BRIg0wqDwG5QT7mreIDPSNeY1l7iU1YN4j9TlMROK0W09Nj3QKwmQ1A&usqp=CAc',
    TRUE
WHERE EXISTS (
    SELECT 1 FROM products WHERE product_name = 'UHS-II SD Card 128GB' AND brand = 'SanDisk'
)
  AND NOT EXISTS (
    SELECT 1 FROM product_images
    WHERE product_id = (SELECT product_id FROM products WHERE product_name = 'UHS-II SD Card 128GB' AND brand = 'SanDisk' LIMIT 1)
      AND is_primary = TRUE
);

INSERT INTO product_images (product_id, url, is_primary)
SELECT
    (SELECT product_id FROM products WHERE product_name = 'Camera Tripod Carbon 1.6m' AND brand = 'Ulanzi' LIMIT 1),
    'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ8SLx-NTprT8gMGsDQrcAcDKQ5OZkxKi-wZkVtCV26Y_KzEB0AaVAGWox6Xz_9nb0CaVzCRbs6Jbjhch6OJNWm8mONW4UkfnMn9XnyLb7s5OSG3edcsFQNQ82jeEaSyc7mashAXEo&usqp=CAc',
    TRUE
WHERE EXISTS (
    SELECT 1 FROM products WHERE product_name = 'Camera Tripod Carbon 1.6m' AND brand = 'Ulanzi'
)
  AND NOT EXISTS (
    SELECT 1 FROM product_images
    WHERE product_id = (SELECT product_id FROM products WHERE product_name = 'Camera Tripod Carbon 1.6m' AND brand = 'Ulanzi' LIMIT 1)
      AND is_primary = TRUE
);

INSERT INTO asset_images (asset_id, url, is_primary)
SELECT
    (SELECT asset_id FROM assets WHERE serial_number = 'CAN-R6II-0001' LIMIT 1),
    'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTxEibHKrlkDg5oh4MSA7qDlmJqlhFtALiHY4UKIkIRtGsAHyDwxHy3ub1U425Zi2wiTetqDt0OhZjyGZxRp-g-ktPNqQAxyLDBHxWjhAq6RPQVaKQNx5ZmreYO7v7ldlpn6CoXRj68QdU&usqp=CAc',
    TRUE
WHERE EXISTS (
    SELECT 1 FROM assets WHERE serial_number = 'CAN-R6II-0001'
)
  AND NOT EXISTS (
    SELECT 1 FROM asset_images
    WHERE asset_id = (SELECT asset_id FROM assets WHERE serial_number = 'CAN-R6II-0001' LIMIT 1)
      AND is_primary = TRUE
);

INSERT INTO asset_images (asset_id, url, is_primary)
SELECT
    (SELECT asset_id FROM assets WHERE serial_number = 'CAN-RF2470-0001' LIMIT 1),
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQim3XQodrFMsCJkMtAnMTRb_xyWYmr6EAfag&s',
    TRUE
WHERE EXISTS (
    SELECT 1 FROM assets WHERE serial_number = 'CAN-RF2470-0001'
)
  AND NOT EXISTS (
    SELECT 1 FROM asset_images
    WHERE asset_id = (SELECT asset_id FROM assets WHERE serial_number = 'CAN-RF2470-0001' LIMIT 1)
      AND is_primary = TRUE
);
