spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/LensoraDB}
spring.datasource.username=postgres
spring.datasource.password=Hoalt@2005

# Tự động cập nhật schema của cơ sở dữ liệu dựa trên các entity đã định nghĩa
spring.jpa.hibernate.ddl-auto=update

# Hiển thị các câu lệnh SQL được thực thi trong console để dễ dàng debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Chỉ định phương thức SQL cho PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cấu hình Jackson để Android nhận định dạng ngày tháng chuẩn
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss